appName: dropwizard-java-example

server:
  type: armeria
  applicationContextPath: /
  ports:
    - port: 8080
      protocol: HTTP
    - port: 8443
      protocol: HTTPS
  ssl:
    keyStore: "keystore.pfx"
    keyStorePassword: "changeit"

logging:
  level: INFO
